# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cd5f083d0c0c8d1ee43f4412aed7bc7fad8f355c4b62324b664bdb3211023aa833be474ab3848d5f50edc121db8cf560e2ea38626c6a784c5fbf4e6706243f0

test:
  secret_key_base: c6b042b0d2bca5bf4b7e881d8db815ba90032906280f3ac459a256ae565a27069f7f0ab54767dda58f9574ff4feaf1d61a943ce63c5bf1c67178f3afc8cede6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
